language: ruby

rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - jruby

gemfile:
  - gemfiles/ar30.gemfile
  - gemfiles/ar31.gemfile
  - gemfiles/ar32.gemfile
  - gemfiles/ar40.gemfile
  - gemfiles/ar41.gemfile
  - gemfiles/ar42.gemfile

sudo: false

services:
  - mysql
  - postgresql

before_script:
  - mysql -e 'create database makara_test;'
  - psql -c 'create database makara_test;' -U postgres

before_install:
  - gem update --system 2.1.11
  - gem --version

matrix:
  exclude:
    - rvm: 1.8.7
      gemfile: gemfiles/ar40.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/ar40.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/ar41.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/ar41.gemfile
    - rvm: 1.8.7
      gemfile: gemfiles/ar42.gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/ar42.gemfile
